# Form implementation generated from reading ui file 'redactirovanie.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import defs
class Ui_redactirovanie_2(object):
    def setupUi(self, redactirovanie_2):
        redactirovanie_2.setObjectName("redactirovanie_2")
        redactirovanie_2.resize(800, 600)
        redactirovanie_2.setStyleSheet("background-color: rgb(218,236,255);")
        self.redactirovanie = QtWidgets.QWidget(parent=redactirovanie_2)
        self.redactirovanie.setObjectName("redactirovanie")
        self.pushButton = QtWidgets.QPushButton(parent=self.redactirovanie)
        self.pushButton.setGeometry(QtCore.QRect(20, 380, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.redactirovanie)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 380, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.redactirovanie)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 460, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.redactirovanie)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 380, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton_4.setObjectName("pushButton_4")
        redactirovanie_2.setCentralWidget(self.redactirovanie)

        self.pushButton.clicked.connect(lambda: defs.go_to_new_file("dobav_rezept.py"))
        self.pushButton_2.clicked.connect(lambda: defs.go_to_new_file("redact_rezept.py"))
        self.pushButton_3.clicked.connect(lambda: defs.go_to_new_file("GL_Ui.py"))
        self.pushButton_4.clicked.connect(lambda: defs.go_to_new_file("udalit_rezept.py"))

        self.retranslateUi(redactirovanie_2)
        QtCore.QMetaObject.connectSlotsByName(redactirovanie_2)

    def retranslateUi(self, redactirovanie_2):
        _translate = QtCore.QCoreApplication.translate
        redactirovanie_2.setWindowTitle(_translate("redactirovanie_2", "MainWindow"))
        self.pushButton.setText(_translate("redactirovanie_2", "Добавить рецепт"))
        self.pushButton_2.setText(_translate("redactirovanie_2", "Редактировать рецепт"))
        self.pushButton_3.setText(_translate("redactirovanie_2", "Назад"))
        self.pushButton_4.setText(_translate("redactirovanie_2", "Удалить рецепт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    redactirovanie_2 = QtWidgets.QMainWindow()
    ui = Ui_redactirovanie_2()
    ui.setupUi(redactirovanie_2)
    redactirovanie_2.show()
    sys.exit(app.exec())
