# Form implementation generated from reading ui file 'udalit_rezept.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import defs

class Ui_udalit_rezept(object):
    def setupUi(self, udalit_rezept):
        udalit_rezept.setObjectName("udalit_rezept")
        udalit_rezept.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        udalit_rezept.setFont(font)
        udalit_rezept.setStyleSheet("background-color: rgb(218,236,255); ")
        self.centralwidget = QtWidgets.QWidget(parent=udalit_rezept)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 201, 20))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 70, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(246,250,255); ")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentIndexChanged.connect(lambda index: self.add_dish(index))
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 500, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(136,155,211);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 500, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"background-color: rgb(136,155,211);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 140, 741, 331))
        self.listWidget.setStyleSheet("background-color: rgb(246,250,255); ")
        self.listWidget.setObjectName("listWidget")
        udalit_rezept.setCentralWidget(self.centralwidget)

        self.pushButton_2.clicked.connect(lambda: defs.go_to_new_file("redactirovanie.py"))
        self.pushButton.clicked.connect(lambda: defs.delete_dish(self.listWidget.currentItem().text()))


        self.retranslateUi(udalit_rezept)
        QtCore.QMetaObject.connectSlotsByName(udalit_rezept)

    def retranslateUi(self, udalit_rezept):
        _translate = QtCore.QCoreApplication.translate
        udalit_rezept.setWindowTitle(_translate("udalit_rezept", "MainWindow"))
        self.label.setText(_translate("udalit_rezept", "Выберите категорию"))
        self.comboBox.setItemText(0, _translate("udalit_rezept", "Первые блюда"))
        self.comboBox.setItemText(1, _translate("udalit_rezept", "Вторые блюда"))
        self.comboBox.setItemText(2, _translate("udalit_rezept", "Закуски"))
        self.comboBox.setItemText(3, _translate("udalit_rezept", "Салаты"))
        self.comboBox.setItemText(4, _translate("udalit_rezept", "Напитки"))
        self.comboBox.setItemText(5, _translate("udalit_rezept", "Десерты"))
        self.pushButton.setText(_translate("udalit_rezept", "Удалить запись"))
        self.pushButton_2.setText(_translate("udalit_rezept", "Назад"))
    def add_dish(self,index):
        self.listWidget.clear()
        kategory= self.comboBox.itemText(index)
        fetch_dish=defs.vabor_category_delete_dish(kategory)
        for dish_name in fetch_dish:
            self.listWidget.addItem(dish_name[1])
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    udalit_rezept = QtWidgets.QMainWindow()
    ui = Ui_udalit_rezept()
    ui.setupUi(udalit_rezept)
    udalit_rezept.show()
    sys.exit(app.exec())
